### ISSUE TITLE
Tracking Antelope upgrade

### ISSUE THREAD

**Issue by chuan137** [sapcc/manila#119]
The customised commits from `stable/xena-m3` as of 22nd July.
> git log --oneline stable/2023.1..stable/xena-m3 --reverse --no-decorate

- [ ] 4a0b7d23d Update .gitreview for stable/xena
- [ ] 8cda34094 Update TOX_CONSTRAINTS_FILE for stable/xena
- [ ] 5f7d557b8 NetApp: properly use netapp_server_port config
- [ ] a1f8f4b29 Adapt CephFS driver to do not try to escape export ip
- [ ] 0fb10e6c5 Drop non-ASCII character from manila config
- [ ] 607e5b8be Xena backporting (#24)
- [ ] b4425c4c9 ccloud: add unit test task for ci
- [ ] eb39b99f6 Force delete and multi xena (#25)
- [ ] 9c88878d1 Fix _get_provisioning_options_for_share() got an unexpected keyword
- [ ] 44b5ba12c early return for _share_replica_update() if there is no active replica
- [ ] a8c20d914 ccloud workaround for https://bugs.launchpad.net/manila/+bug/1918845
- [ ] 2c4bb1612 ccloud: add security service association for multi
- [ ] f8320d284 remove travis-ci config
- [ ] 64bfdc118 add python-agentliveness to custom req
- [ ] f92a968a9 ccloud: fix http exceptions in revert to snapshot
- [ ] 53681a5b4 ccloud: add share_instance updated_at field to list index
- [ ] 1eb49289c ccloud: add extra spec 'netapp:max_files_multiplier'
- [ ] 01b9d7ce4 ccloud fix of https://bugs.launchpad.net/manila/+bug/1964592
- [ ] 109e7bd59 Revert "ccloud: ignore unmount errors"
- [ ] bdb98666d ccloud: wait 3 seconds after sending unmount command
- [ ] 5ba5963fe NetApp: max_files cannot be set on dp volumes
- [ ] 01446c154 add gmr to wsgi
- [ ] 77b4e2d47 ccloud: do not touch nfs v4.0 if it has not been enabled
- [ ] 97e5572c2 ccloud: added pymemcache custom-requirement
- [ ] 9236e7223 ccloud: ensure max_files but allow backend overwrite
- [ ] fbdc256e7 ccloud: use existing share_utils to get hostname from host state
- [ ] cac9a595d ccloud: don't replicate to same backend
- [ ] f095931f5 ccloud: catch StorageResourceNotFound in ensure_shares
- [ ] 4474228ae ccloud: put access rules in state error back to queue to apply
- [ ] ba476871d remove ccloud reexport flag in netapp _get_vserver
- [ ] 39ed2a413 amend fix for https://bugs.launchpad.net/manila/+bug/1964592
- [ ] 2fa6851f7 ccloud: every 7 days re-try to apply access rules in error state
- [ ] 3f58860f1 [netapp] retry requests
- [ ] dc631254e ccloud fix of https://bugs.launchpad.net/manila/+bug/1971710
- [ ] c21f40089 ccloud: don't do set union/intersection in affinity validation
- [ ] 9f36ac05b ccloud: fix missing share type name in share_instance dict
- [ ] 95578d3a4 ccloud: use ldaps for cifs and report channel binding in pool capabilities
- [ ] 59da68a54 Fix DriverFilter/GoodnessWeigher string evaluations
- [ ] e43a45a4b ccloud: keep share servers with sec services on error
- [ ] 619d2abc8 Add config option reserved_share_extend_percentage
- [ ] e212a39a2 Set DC discovery-mode to 'none' in case server specified
- [ ] 278f336dd Allow disabling NFSv4.0
- [ ] 51e5070b2 Rollback quota when share network create API fails.
- [ ] b3a105d54 Add jaeger-client for osprofiler needs (#46)
- [ ] cf1cb60d2 Allow update of password in security service (#47)
- [ ] 5b5b4d31b Adds support max share extend size limited by share_type
- [ ] cc7dd4d5b Enable osprofiler rpc trace for WSGI.
- [ ] aea217f1e ccloud: Enable logical space reporting for new shares (#51)
- [ ] e294ebb45 ccloud: Disable cross-volume-deduplication to prevent metadata from filling volume (#52)
- [ ] 20f268b19 Add defaultadsite to security service
- [ ] 6f47e434a ccloud: fix disabling cross-volume-deduplication
- [ ] 9bd0fc953 [NetApp] Consider last transfer size and error for replica state
- [ ] 05c6f8017 Destroy services from DB on stop()
- [ ] 796394159 Allow resync if replica is out_of_sync
- [ ] 40e6ca179 SAPCC: cifs certificates support loading for DER format
- [ ] 3503a199a SAPCC: re-introduce 77b4e2d47b892e6b369790161257d3bd3c4027f4
- [ ] 4523c603f [NetApp] catch errors on getting vserver when reusing share server
- [ ] 635608f8e init share server updated_at field
- [ ] 03a3b440d create replica: allow to specify uuid
- [ ] c9da39545 [NetApp] fallback to cifs-server force delete on vserver cleanup
- [ ] 48181c5ea new replica state
- [ ] 503829a20 NetApp: Use cluster client in non-vserver contexts
- [ ] 624833727 Force share server selection on nondisruptive migration
- [ ] 0f26ef47c [Netapp] Change asynchronous SnapMirror schedules
- [ ] 188ad08cc Revert "new replica state"
- [ ] 22563b00c Revert "Allow resync if replica is out_of_sync"
- [ ] eb2abdeb3 [NetApp] guard already existing cifs access
- [ ] 0b649e56e ccloud: reduce RPO to 20 minutes
- [ ] be21ca1ae sapcc: tox.ini uses TOX_CONSTRAINTS_FILE
- [ ] 67376d8ba sapcc: use tox pre 4.0
- [ ] a071e2712 Filter on size based on operation.
- [ ] 0135d7310 sapcc: lower unmount log to warning
- [ ] 008d35c57 (SAPCC) Add warning on failures during replica promotion
- [ ] 3f1a8f98f sapcc: fix ensure for replicas
- [ ] e9edd8051 sapcc: update schedule of existing snapmirrors
- [ ] 73c6771d4 svm migration across physical networks with multiple port bindings (#60)
- [ ] f9012cc46 Apply access rules on new share replicas
- [ ] 43b361600 Fix tox4 errors.
- [ ] 40110c409 netapp: ignore duplicate entry errors on cert install
- [ ] f76afdb14 It is okay to not have server and default_ad_site either
- [ ] 3ac4c733c check_exec: /usr/bin/python3 bad interpreter
- [ ] 8a14ba519 ensure_share_server: catch NetApp errors
- [ ] b1a612ee5 preload share server backend details in manager
- [ ] 18141f218 tox4 needs allowlist_externals for fast8
- [ ] f2ab38cd5 allow overide of basepython with TOX_PYTHON env
- [ ] 428ebd8c9 NetApp: move split job to end
- [ ] 65d9d18de NetApp set_volume_max_files: additional guard
- [ ] 5d7967a8f SAPCC: increase purge failures to log error
- [ ] d113cfe2a sapcc: add new digicert root ca
- [ ] a217b9b29 improve db calls in periodic replica tasks
- [ ] 390b5e194 add rate limit middleware
- [ ] 5b2740845 sqlalchemy: add generic repr to base model
- [ ] 7c91e2faf Improve scheduler performance when thin provisioning
- [ ] 431767b09 Recreate security cert during vserver create.
- [ ] f0bcf8538 sapcc: add netapp_hardware_state state option
- [ ] a8de56481 ensure share server: skip default policy rules
- [ ] 376891e5d SAPCC: logical space settings as 'False' for hypervisor storage (#83)
- [ ] fee71bfba propogate port quota limit exceeded error (#91)
- [ ] 68874420b Ignore delete share servers in ensure_driver_resources
- [ ] d5a81dd30 sapcc: try blocks for all promote additions
- [ ] 79078c2f4 sapcc: go back to default settings for nfsv41 (#95)
- [ ] 5f08591c5 Add error handling in modify_volume()
- [ ] 40465e661 sapcc: skip ensure share server on flag
- [ ] d62aa466c skip periodic update on replicas in 'error_deleting'
- [ ] 37eb204f5 NetApp: don't raise filesys-size-fixed on svm migrate
- [ ] 37b974a6c sapcc: report cifs capability for CVE-2022-38023
- [ ] 921fb769f Handle successful deletion of snapshot if quota commit fails
- [ ] 9a914aaa6 [API] Validate display name/description length
- [ ] 8fdcac4bd fix scheduler's anti affinity filter (#111)
- [ ] 7a75f4144 Add pyreloader to custom requirements (#115)
- [ ] ac5a6263d Fix duplicate entries of share_server_backend_details
- [ ] 8b71ff83a Stop clone while deleting child shares. (#114)
- [ ] c05497c19 Soft delete volumes when they have clones (#116)

**Comment by chuan137** [comment]
Above list is the commits that appears in `stable/xena-m3`, but not in 'stable/2023.1` (Antelope upstream). The list contains those commits that have same content but different commit id in Antelope. I tried to find them by comparing modified files and similar commit message. I also double checked the content to make sure they have identical changes.

There are a few commits that need to have a closer look. There are  similar but have slight different changes.

> vimdiff <(git show 59da68a54) <(git show a2ebe1eb9)
vimdiff <(git show 619d2abc8) <(git show 6431b86f1)
vimdiff <(git show e212a39a2) <(git show 8f2303046)
vimdiff <(git show 9bd0fc953) <(git show 6e8ed59a9)
